# Generated by Selenium IDE
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys


@pytest.fixture
def browser():
    driver = webdriver.Chrome()
    yield driver
    driver.quit()


def test_creazione_evento_pubblico_sistema(browser):
    browser.get("http://127.0.0.1:5000/home_organizzatore")

    login(browser, "d.maria@gmail.com", "password")

    browser.find_element(By.LINK_TEXT, "Crea Evento Pubblico").click()

    inserisci_dati_evento(browser, "2024-02-01", "50", "Compleanno di Antonio", "byte_array_immagine", "ruolo",
                          "Compleanno", False,
                          ["fornitore1", "fornitore2"], ["servizio1", "servizio2"], "100.0", "20:00",
                          "Nome dell'evento",
                          "Via dell'evento", "Lazio", "id_del_fornitore")

    browser.find_element(By.CSS_SELECTOR, ".button").click()

    assert "L'evento pubblico è stato creato con successo!" in browser.page_source


def login(browser, email, password):
    browser.find_element(By.NAME, "email").send_keys(email)
    browser.find_element(By.NAME, "password").send_keys(password)

    browser.find_element(By.CSS_SELECTOR, ".left .movimentoH1").click()

    WebDriverWait(browser, 10).until(EC.url_changes("http://127.0.0.1:5000/home_organizzatore"))
    assert "Benvenuto" in browser.page_source


def inserisci_dati_evento(browser, data, n_persone, descrizione, locandina, ruolo, tipo, is_pagato, fornitori_associati,
                          servizi_associati, prezzo, ora, nome, via, regione, id_fornitore):
    browser.find_element(By.ID, "data-evento").send_keys(data)
    browser.find_element(By.ID, "n_invitati").send_keys(n_persone)
    browser.find_element(By.NAME, "descrizione").send_keys(descrizione)

    locandina_input = browser.find_element(By.NAME, "locandina")
    locandina_input.send_keys(locandina)

    ruolo_dropdown = browser.find_element(By.ID, "ruolo_evento")
    ruolo_dropdown.find_element(By.XPATH, f"//option[. = '{ruolo}']").click()

    tipo_dropdown = browser.find_element(By.ID, "tipo_evento")
    tipo_dropdown.find_element(By.XPATH, f"//option[. = '{tipo}']").click()

    if is_pagato:
        browser.find_element(By.NAME, "is_pagato").click()

    for fornitore in fornitori_associati:
        browser.find_element(By.NAME, "fornitori_associati").send_keys(fornitore, Keys.RETURN)

    for servizio in servizi_associati:
        browser.find_element(By.NAME, "servizi_associati").send_keys(servizio, Keys.RETURN)

    browser.find_element(By.NAME, "prezzo_biglietto").send_keys(prezzo)
    browser.find_element(By.NAME, "ora-evento").send_keys(ora)
    browser.find_element(By.NAME, "nome_evento").send_keys(nome)
    browser.find_element(By.NAME, "via_evento").send_keys(via)

    regione_dropdown = browser.find_element(By.NAME, "regione_evento")
    regione_dropdown.find_element(By.XPATH, f"//option[. = '{regione}']").click()

    browser.find_element(By.NAME, "id_fornitore").send_keys(id_fornitore)
