# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestCreazionediuneventoprivato():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def wait_for_window(self, timeout=2):
        time.sleep(round(timeout / 1000))
        wh_now = self.driver.window_handles
        wh_then = self.vars["window_handles"]
        if len(wh_now) > len(wh_then):
            return set(wh_now).difference(set(wh_then)).pop()

    def test_creazionediuneventoprivato(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.set_window_size(959, 959)
        self.driver.find_element(By.NAME, "email").send_keys("simonettidaria@gmail.com")
        self.driver.find_element(By.NAME, "password").send_keys("Ciao.123")
        self.driver.find_element(By.CSS_SELECTOR, "lord-icon").click()
        self.driver.find_element(By.NAME, "accesso").click()
        self.driver.find_element(By.NAME, "email").send_keys("simonettidaria@gmail.com")
        self.driver.find_element(By.NAME, "password").send_keys("Ciao.123")
        self.driver.find_element(By.CSS_SELECTOR, ".left .movimentoH1").click()
        self.driver.find_element(By.NAME, "email").send_keys("simonettidaria@gmail.com")
        self.driver.find_element(By.NAME, "password").send_keys("Ciao.123")
        self.driver.find_element(By.ID, "data-evento").click()
        self.driver.find_element(By.ID, "data-evento").send_keys("2024-03-14")
        self.driver.find_element(By.ID, "n_invitati").click()
        self.driver.find_element(By.ID, "n_invitati").send_keys("23")
        self.driver.find_element(By.CSS_SELECTOR, ".button").click()
        self.driver.find_element(By.NAME, "email").send_keys("simonettidaria@gmail.com")
        self.driver.find_element(By.NAME, "password").send_keys("Ciao.123")
        self.driver.find_element(By.CSS_SELECTOR, "#g\\.verdoliva\\@gmail\\.com > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#\\36 5ae6a257f1fda0b9720d66c > a").click()
        assert self.driver.switch_to.alert.text == "\"Servizio aggiunto al carrello\""
        self.driver.find_element(By.LINK_TEXT, "Visualizza").click()
        self.driver.find_element(By.CSS_SELECTOR, "#\\36 5ae6ab77f1fda0b9720d67d > a").click()
        assert self.driver.switch_to.alert.text == "\"Servizio aggiunto al carrello\""
        self.driver.find_element(By.CSS_SELECTOR, "#r\\.revellino\\@gmail\\.com > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#\\36 5ae6c667f1fda0b9720d697 > a").click()
        assert self.driver.switch_to.alert.text == "\"Servizio aggiunto al carrello\""
        self.driver.find_element(By.LINK_TEXT, "Visualizza").click()
        self.driver.find_element(By.CSS_SELECTOR, "#\\36 5ac00db2efd536fe39814eb > a").click()
        assert self.driver.switch_to.alert.text == "\"Servizio aggiunto al carrello\""
        self.vars["window_handles"] = self.driver.window_handles
        self.driver.find_element(By.CSS_SELECTOR, ".IconContainer").click()
        self.vars["win775"] = self.wait_for_window(2000)
        self.driver.switch_to.window(self.vars["win775"])
        self.driver.find_element(By.NAME, "email").send_keys("simonettidaria@gmail.com")
        self.driver.find_element(By.NAME, "password").send_keys("Ciao.123")
        self.driver.find_element(By.NAME, "descrizione").click()
        self.driver.find_element(By.NAME, "descrizione").send_keys("Compleanno di Antonio")
        self.driver.find_element(By.NAME, "nome_festeggiato").send_keys("Tonino")
        self.driver.find_element(By.CSS_SELECTOR, ".icon").click()
        self.driver.find_element(By.NAME, "email").send_keys("simonettidaria@gmail.com")
        self.driver.find_element(By.NAME, "password").send_keys("Ciao.123")

