# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestAggiungiServizioOfferto():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_aggiungiServizioOfferto(self):
        self.driver.get("http://127.0.0.1:5000/fornitori")
        self.driver.set_window_size(2576, 1416)
        self.driver.find_element(By.ID, "modal-buttonAF").click()
        self.driver.find_element(By.ID, "description").click()
        self.driver.find_element(By.ID, "description").send_keys("Sala Maggiore")
        self.driver.find_element(By.ID, "price").click()
        self.driver.find_element(By.ID, "price").send_keys("250")
        self.driver.find_element(By.ID, "fileInput").click()
        self.driver.find_element(By.ID, "fileInput").send_keys(
            "C:\\fakepath\\trullo-trulli-ristoranti-hotel-affitto.webp")
        self.driver.find_element(By.CSS_SELECTOR, "form > .modalButtonAF").click()

